# Generated by Django 2.0.5 on 2019-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=50)),
                ('batch', models.IntegerField()),
                ('dept', models.CharField(max_length=3)),
                ('section', models.CharField(max_length=3)),
            ],
        ),
    ]
